name = input("Ingrese su nombre conpleto: ")
print("your name in uppeCase: "+name.upper())
print("your name in lowerCase: "+ name.lower())
print("your name in captalizeCase: " + name.title())
input()